### ISSUE TITLE
[feat] Optimize raito to reduce steps using lookup tables and type-specific optimizations

### ISSUE THREAD

**Issue by Th0rgal** [keep-starknet-strange/raito#268]
## Description
The goal of this feature is to optimize raito by reducing the number of computational steps. This will be achieved through the use of lookup tables and by implementing type-specific optimizations where possible.

## Tasks
- [ ] Fast pow2 using lookup table
- [ ] Fast shr for u64
- [ ] Optimize bits_to_target with shr_u64 and early returns
- [ ] Optimize next_power_of_two
